### ISSUE TITLE
Operator should default to the watched namespace

### ISSUE THREAD

**Issue by zerg-junior** [zalando-incubator/postgres-operator#155]
Right now the operator seems to rely on the access to the default namespace. In particular, it tries to fetch security tokens from the default namespace instead of the watched one.

**Comment by alexeyklyukin** [comment]
That would make the operator behavior inconsistent with the rest of the Kubernetes (the page https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ says that for the objects without the explicitly defined namespace the default one is used). Also, what happens if the operator watches multiple namespaces and every one of them contain slightly different security token?

**Comment by Jan-M** [comment]
First we should not mix what does not belong together, so the whole discussion about multiple namespace support is a different requirement and feature and may change some things.

However in this case we need to clearly support the operator to run in an arbitrary specified namespace. And I find it confusing that we have to spec the namespace everywhere, this is not a user friendly default behavior.

For the operator we should simply default to the namespace the operator is running in for every lookup of config and token objects, that is very transparent and easy to understandable. And is aligned with the secrets not being readable across namespaces.

**Comment by erthalion** [comment]
> Operator should default to the watched namespace
> That would make the operator behavior inconsistent with the rest of the Kubernetes (the page https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ says that for the objects without the explicitly defined namespace the default one is used)

If I understand things correctly, you want to deploy postgres-operator to watched namespaces instead of default one. What do you think about separate configuration options for both of these things, i.e. watched namespaces and deployment target namespace? In this case if target namespace is not defined or empty, then it goes to default  namespace. And watched namespaces will be configured and treated separately.

**Comment by alexeyklyukin** [comment]
@erthalion the deployment target namespace is configured in the deployment manifest of the operator , while the watched namespace is controlled by  the environment variable ``WATCH_NAMESPACE`` in the operator deployment; that implies they are already separated.

The question in the title of this thread is what should we do if we don't have any namespace specified in the ``WATCH_NAMESPACE`` (or the equivalent future configuration parameter in the operator configuration). Our choices are either to listen to the ``default`` namespace, or to listen to the  namespace the operator is deployed to.  I don't see any issues with sticking to the ``default`` namespace for that case, as any non-default namespace we want the operator to listen to (mostly for the testing purposes) is known during the deployment time and can be specified as a value of the ``WATCH_NAMESPACE`` variable in the operator manifest.
