### ISSUE TITLE
Question: Is postgres-operator open to supporting more granular CRDs?

### ISSUE THREAD

**Issue by t3hmrman** [zalando-incubator/postgres-operator#253]
Hey all, thanks for the great work on `postgres-operator` (and of course supporting tech like `spilo` and `patroni`) -- I was wondering if more granular CRDs (e.g. `PostgresDB`, `PostgresSchema`, and maybe even `PostgresTable`) are considered inside the scope (or future scope) of this project.

In the future I'd like to contribute something like this, because it's often what I want out of an operator, especially in a shared environment (or for example with a multi-tenant postgres setup). There's a bit of auto-vivication that would be required here -- for example if someone requests a `PostgresDB`, and gives a cluster name, it would be required for `postgres-operator` to find the cluster if it already exists or create it (this could be configurable). In addition, RBAC permission checking would have to be expanded.

I have no problem building this into another operator that maybe relies on `postgres-operator`, but wanted to at least ask first.

**Comment by alexeyklyukin** [comment]
We choose a different approach by configuring databases and users inside the manifest (actually, there are 3 places where the users can be specified: the manifest for robot users, ``infrastructure roles`` for cluster-wide users and ``teams api`` for human users that should authenticate via the pam Oauth2 module). This also includes creating databases together with the roles that own them after the cluster has been created when the manifest is updated. The spilo image the operator created postgres clusters are based at at also defines a ``set_user`` extension for each databases in order to elevate users that are in the admin role (that is assigned to all users coming from the teams api by default) to whatever non-superuser role that choose to, including roles that are defined in the manifest as DB owners.

We choose not to manage objects on a more fine-grained (like schemas, tables and so on) today, as IMO this is the task of the user/application accessing the database and SQL language is much better at doing it than Kubernetes manifests.

However, we were discussing running arbitrary SQL queries on the clusters by the operator at some point. If we go this route, then having a special CRD object for that sounds like a good idea.

**Comment by Jan-M** [comment]
I am pretty much aligned with Oleksii's answer, the postgres-operator's responsibility stops once databases are created within the cluster and roles are provisioned. There are good existing solutions like Flyway to take it from there and that also allow testing schema setup locally.

We have the roles and databases within the manifest to allow a seamless deployment experience and e.g. employee roles and infrastructure roles are something common to all PostgreSQL clusters.

**Comment by t3hmrman** [comment]
Hey @alexeyklyukin  and @Jan-M , thanks for the answer -- what I'm envisioning seems very much like it should be implemented in a sort of side-by-side operator or meta operator that sits above postgres-operator (assuming it should be created at all). 

It's very likely that the current functionality (proactive & reactive DB + role + user createion) is more than enough, I was preoccupied with the idea of two different microservices sharing the same database, but splitting up by schema or even table, and maybe even allowing them to read other schemas/tables but never write -- which might be a silly optimization to make to begin with, since [postgres_fdw](https://www.postgresql.org/docs/9.3/static/postgres-fdw.html) exists.

I'll go ahead and close the ticket since I think the answer is pretty definitive and makes sense.
