### ISSUE TITLE
Create the pod service account if missing during sync

### ISSUE THREAD

**Issue by mgomezch** [zalando-incubator/postgres-operator#280]
During processing of a sync event for a database cluster, the pod service account should be queried on the database cluster's target namespace, and if the pod service account is missing, then it should be created.

Note that this is a *separate* issue from deciding what to do if a service account is found in the cluster's target namespace, in which case syncing is unfortunately more complex.

(For now, an effective workaround for any existing database clusters that fail to start due to a missing service account is to deploy another database cluster to the same namespace, because then the service account creation logic will kick in and the stuck StatefulSet should heal.)

**Comment by zerg-junior** [comment]
Won't fix for now since the motivation behind this issue is a specific use case, namely:
1. a PG cluster is started under the older operator version that does not check/deploy  a pod service account  during cluster creation
2.  The cluster won't able to start due to the lack of the service account 
3. At this moment, the operator is upgraded to the version that deploys service account during creation.

i see this situation is a quite unlikely known issue  and not worth a specific workaround in `Sync()` that would affect all clusters.
