### ISSUE TITLE
Different env var for separate manifests

### ISSUE THREAD

**Issue by SauravPrakash98** [zalando-incubator/postgres-operator#334]
I am new to Postgres-operator. I want to have Wal backup of only one Postgres server while creating separate manifest through the same operator. So how to add custom env var directly to manifest without using referenced Configmap(as it would apply these variables to all the pods).

**Comment by alexeyklyukin** [comment]
@SauravPrakash98 the operator is build on the assumption that every single cluster managed by it has the same way of producing backups. Therefore, there is no per-cluster configuration for WAL-e specific parameters. 

However, if you are running on a fairly modern Kubernetes (I think 1.7 and above) you can use Pod Presets (https://kubernetes.io/docs/concepts/workloads/pods/podpreset/#) to inject the necessary variables (WAL_S3_BUCKET should suffice) in your pods. For that, you need to set the selector of the pod preset to the labels you use to indicate the cluster name, so that it would only catch the clusters you need.

**Comment by Jan-M** [comment]
You can build a custom docker image if you really need this, in the docker image you disable/overwrite the wal-e config and you can then set this docker image in the postgresql manifest.

**Comment by SauravPrakash98** [comment]
Thank you very much!
