### ISSUE TITLE
Is the fact posgres version is out of date a problem?

### ISSUE THREAD

**Issue by mjschmidt** [zalando-incubator/postgres-operator#374]
I don't know if its worth updating the postgres versions. If it is, just let me know what I would need to change. I am thinking it would be the docker images used in this deploy? 

I see a dockerfile here, but I don't see the build folder to copy that stuff into a container.

Let me know. Love the potential of this project!

**Comment by alexeyklyukin** [comment]
@mjschmidt 

The operator relies on the Spilo docker image (https://github.com/zalando/spilo/), which contains PostgreSQL and Patroni among others. You won't be able to use it with a generic Postgres image, i.e. from the docker hub. At the moment Spilo includes all released and supported Postgres versions, from 9.3 to 10 and will be updated to include upcoming Postgres 11 once it is released. Spilo includes a lot of extensions, such as postgis or plv8, some postgres related apps, such as pgbouncer, and since it is open-source, you can customize it to your needs.

As you've mentioned updating postgres versions I am wondering if you are trying to migrate your existing clusters to those managed by the operator? If so, what is your current setup?

> I see a dockerfile here, but I don't see the build folder to copy that stuff into a container.

The Dockerfile is for the operator, which runs in a separate container.
