### ISSUE TITLE
Bootstrap options missing ?

### ISSUE THREAD

**Issue by aelbarkani** [zalando-incubator/postgres-operator#428]
We are considering Patroni Operator for production databases in Kubernetes, but it seems it's not possible at the moment to customize bootstrap options, building replicas and standby clusters as described here:
https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#custom-bootstrap
Is there a hidden option in the operator we didn't see to do this?

**Comment by erthalion** [comment]
As far as I understand, all the Patroni related options are described [here](https://github.com/zalando-incubator/postgres-operator/blob/45c89b3da4f72a0ebb1a683fec5a8ffdd76ce20e/pkg/apis/acid.zalan.do/v1/postgresql_type.go#L98), and yeah, looks like they don't include custom bootstrap options. But it sounds like a good feature to add, especially since we already had this in mind. At the moment I believe you can workaround this by building your own spilo image, where you can include any necessary options.

**Comment by erthalion** [comment]
I'm going to close the issue, feel free to reopen if you need more information.
