### ISSUE TITLE
pg.status is not set to running after successfull UPDATE

### ISSUE THREAD

**Issue by redbaron** [zalando-incubator/postgres-operator#467]
When we update PG object,  operator does all the right thing to pods, but then leaves pg.status as `Updating`. Only on a subsequent resync it catches up and sets .status to `Running`

I pasted logs to gist where UPDATE from 18:04 is seen and then subsequent SYNC at 18:17 , it is not seen from logs, but it is latter which correctly sets pg.status to "Running"

https://gist.github.com/redbaron/4bb47e430a12194b4a0b64e283076b25

**Comment by sdudoladov** [comment]
that is kind of strange because they use similar code for updating the status ([Sync](https://github.com/zalando-incubator/postgres-operator/blob/7907f95d2fdefc4d35b3f69dacfd8af56fc4e72b/pkg/cluster/sync.go#L27) / [Update](https://github.com/zalando-incubator/postgres-operator/blob/c70905ae8b443c62322287a5e2f356cce7d00f15/pkg/cluster/cluster.go#L494))

1. Is the issue reproducible on minikube ?
2. which command do you use to check status ?
