### ISSUE TITLE
Replica fails to initialize from s3 with wale backups. Instance profile has no s3 access since it's shared by multiple pods.

### ISSUE THREAD

**Issue by valer-cara** [zalando-incubator/postgres-operator#488]
When scaling a cluster that uses wal-e backups, replica fails to initialize due to wrong s3 permissions in the `wal-e-wal-fetch.sh` script in spilo, which is called with `--aws-instance-profile`.

In my case, i don't have dedicated pg machines, so i haven't allowed the machine to access that backups bucket. Instead I pass the aws env vars to the pg pods, but the scripts don't account for that.

Spilo forces the wal-e based restore command to use the instance credentials, even if AWS_ACCESS_KEY/AWS_SECRET_KEY_ID are present. See [here](https://github.com/zalando/spilo/blob/87f081c918da8e4d0b390eddb550da47730723e0/postgres-appliance/scripts/restore_command.sh#L26)

Combined with the fact that the replication slots are initially set to inactive as the replica boots so if it takes too long for base backup-fetch, those WAL files are deleted from the master - so it can't start this way either.

In one instance i manually removed that `--aws-instance-profile` flag from the restore_command.sh script, but that's not great.

Do you have any suggestions re. this situation? Thanks!

**Comment by sdudoladov** [comment]
@CyberDem0n do you have suggestions ?

**Comment by CyberDem0n** [comment]
> When scaling a cluster that uses wal-e backups, replica fails to initialize due to wrong s3 permissions in the wal-e-wal-fetch.sh script in spilo, which is called with --aws-instance-profile

It was always like this. On AWS we always rely on AWS instance profile. https://github.com/zalando/spilo/commit/0778db8ac58d5f39433ebc58095e5b5d3e58e2b8#diff-e6c13f6ffe3c8b153ee81ed7ce44235bL17
And actually this is not the only place where such argument is used: https://github.com/zalando/spilo/search?q=--aws-instance-profile&unscoped_q=--aws-instance-profile

I am not sure how exactly wal-e is handling the case when `--aws-instance-profile` is set and at the same time AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY are available, but they probably also could fail.


> Combined with the fact that the replication slots are initially set to inactive as the replica boots so if it takes too long for base backup-fetch, those WAL files are deleted from the master - so it can't start this way either.

This is strange. What version of spilo and postgres do you use? Starting from version [1.5.1](https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L1613) Patroni immediately reserves wals on postgres 9.6+.

> In one instance i manually removed that --aws-instance-profile flag from the restore_command.sh script, but that's not great.

Indeed, that should be fixed. Here is the idea:
* Start using `AWS_INSTANCE_PROFILE=1` environment variable instead of `--aws-instance-profile` argument. It actually will also simplify a lot of scripts.
* https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py should write 1 into the `AWS_INSTANCE_PROFILE` file in the envdir if it detects that we are on AWS and AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY aren't set.
